name: Jesse Silverberg
title: Jesse Silverberg
description: Jesse Silverberg
url: https://jessesilverberg.com
repository: https://github.com/jessesilverberg/jessesilverberg.github.io
google_analytics_id: G-3EKY3YJDBS
logo: "/img/favicon.png"
social:
  name: Jesse Silverberg
  links:
    - https://github.com/jessesilverberg
    - https://twitter.com/SilverbergJesse

author:
  twitter: silverbergjesse

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "img/*.pdf"
    values:
      sitemap: false

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
