name: Jesse Silverberg
title: Jesse Silverberg
description: Jesse Silverberg
url: https://jessesilverberg.com
repository: https://github.com/jessesilverberg/jessesilverberg.github.io
google_analytics_id: UA-149872984-1
logo: "/img/profile.ico"
social:
  name: Jesse Silverberg
  links:
    - https://github.com/jessesilverberg
    - https://twitter.com/SilverbergJesse

author:
  twitter: silverbergjesse

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
